### User Account Creation Test

POST http://localhost:5158/signup
Content-Type: application/json

{
    "username": "test",
    "password": "gnlkfjdsngkjlfds",
    "email": "test@testing.test",
    "ownerotp": "045462"
}

### Session Create Test

POST http://localhost:5158/login
Content-Type: application/json

{
    "email": "test@testing.test",
    "password": "gnlkfjdsngkjlfds"
}

### Tag Create Test

POST http://localhost:5158/tags
X-Api-Key:{{apiKey}}
Content-Type: application/json

{
    "name": "test",
    "colour": "#ff0000"
}

### Tag Delete Test - pt.1


POST http://localhost:5158/tags
X-Api-Key:{{apiKey}}
Content-Type: application/json

{
    "name": "tag-delete-test",
    "colour": "#ff0000"
} 

> {% client.global.set("delete-tag-id", response.body.id) %}



### Tag Delete Test - pt.2

DELETE http://localhost:5158/tags/{{delete-tag-id}}
X-Api-Key:{{apiKey}}