@ownerotp =481020
@email = {{$random.internet.safeEmailAddress}}

### User Account Creation Test

POST http://localhost:5158/signup
Content-Type: application/json

{
    "username": "test",
    "password": "{{test_password}}",
    "email": "{{email}}",
    "ownerotp": "{{ownerotp}}"
}

### Session Create Test

POST http://localhost:5158/login
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{test_password}}"
}

> {%
 console.log(response.body)
 client.global.set("api_key", response.body) %}

### Tag Create Test

POST http://localhost:5158/tags
X-Api-Key:{{api_key}}
Content-Type: application/json

{
    "name": "tag-delete-test"
}

> {%
console.log(response.body)
client.global.set("delete_tag_id", response.body.id) %}

### Tag Delete Test - pt.2

DELETE http://localhost:5158/tags/{{delete_tag_id}}
X-Api-Key: {{api_key}}